# This is a basic workflow to help you get started with Actions
name: Connect to an AWS role from a GitHub repository

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  
  AWS_REGION : eu-west-1 #Change to reflect your Region

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install Python dependencies and CDK
        run: |
          python -m pip install --upgrade pip
          # install your Python dependencies here
          npm install -g aws-cdk
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: cdk deploy
        run: |
          dotnet test tests/ProductAPI.Tests/
      - name: cdk deploy
        run: |
          cd infra
          cdk deploy --require-approval=never
